### ISSUE TITLE
BOM File

### ISSUE THREAD

**Issue by Rowlet311** [ChrisChrisLoLo/idawgz32#1]
Hello, I would preface this by saying that I'm a total noob when ordering pcb's. I have been trying to order this on JLCpcb, as recommended, but I have been unable to find a compatible BOM file. I wasn't sure if it was right to ask this here, so please correct me if needed. Thank you!

**Comment by locoboy24** [comment]
I used the BOM and pick and place file in v2/pcb/idawgz32/output.zip. The BOM is called idawgz32-modified.csv and the pick and place file is called idawgz32-top-pos-modified.csv

**Comment by Rowlet311** [comment]
Thank you!
